# Generated by Django 3.2.5 on 2022-01-06 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListedShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdbId', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=300)),
                ('imdbRating', models.FloatField()),
                ('year', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
                ('listOwner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.list')),
                ('userOwner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
