# Generated by Django 3.2.5 on 2022-01-08 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_listedshow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='listName',
        ),
    ]
