# Generated by Django 3.2.5 on 2022-01-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_list_listname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listedshow',
            name='imdbRating',
            field=models.CharField(max_length=4),
        ),
    ]
